# Go CI

name: Building, Testing and deploying a module

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        run: go test -v ./...
  linter:
    name: golangci linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
  release-snapshot:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Create snapshot
        id: snapshotter
        uses: DevourTech/snapshotter@v1.0.0
        with:
          BASE_VERSION: v0.0.0
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_USERNAME: "DevourTech"
          GITHUB_REPOSITORY: "devourKV"
      - name: Release snapshot
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.snapshotter.outputs.SNAPSHOT_VERSION }}",
              sha: context.sha
            })
